[package]
name = "vredditor-api"
version = "0.1.0"
authors = ["Billy J Rhoades II <me@brod.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2"
rand = "0.7"
log = "0.4"
env_logger = "0.8"
anyhow = "1.0"

bytes = "=0.5"
# XXX: After tokio 1.0 migration, move back to reqwest.
hyper = { version = "0.14", features = [ "client", "http1", "http2", "stream", "runtime" ] }
hyper-rustls = "0.22"

serde = "1.0"
serde_json = "1.0"

# tokio = { version = "=0.3.6", default-features = false, features = ["rt-multi-thread", "macros", "sync", "net", "io-util", "time", "process", "fs"] }
tokio = { version = "1.0", default-features = false, features = ["full"] }
# pins pin-project to 0.2.0, which makes tokio-tungstenite play nice
# websocket-codec = "=0.4.0"

futures = { version = "0.3" }
futures-util = { version = "0.3", default-features = false, features = ["async-await", "sink", "std"] }
async-trait = "0.1"

prost = "0.6"

# XXX: After tokio 1.0 migration, change to peroper proper version
[dependencies.rusoto_core]
git = "https://github.com/benesch/rusoto"
branch = "tokio-10"

# XXX: After tokio 1.0 migration, change to peroper proper version
[dependencies.rusoto_s3]
git = "https://github.com/benesch/rusoto"
branch = "tokio-10"

# XXX: After tokio 1.0 migration, change to peroper proper version
[dependencies.tokio-tungstenite]
git = "https://github.com/dnaka91/tokio-tungstenite"
features = ["connect", "stream"]
branch = "tokio-1.0"

[build-dependencies]
prost-build = "0.6"
glob = "0.3"
anyhow = "1.0"


[lib]
name = "lib"
path = "src/lib/lib.rs"